# æ˜¯å¦å…è®¸ç”¨æˆ·åˆ›å»ºç©ºç™½ Issueï¼ˆå»ºè®®è®¾ä¸º falseï¼Œå¼ºåˆ¶ä½¿ç”¨æ¨¡æ¿æˆ–æŸ¥çœ‹ä¸‹æ–¹é“¾æ¥ï¼‰
blank_issues_enabled: true

# åœ¨æé—®ç•Œé¢é¡¶éƒ¨æ˜¾ç¤ºçš„è‡ªå®šä¹‰è”ç³»/æŒ‡å¼•é“¾æ¥
contact_links:
  - name: "ğŸš© ç¬¬ä¸€æ­¥ï¼šæŸ¥é˜…é¡¹ç›®æ–‡æ¡£"
    url: https://github.com/liuchuancong/pure_live
    about: "åœ¨æé—®ä¹‹å‰ï¼Œè¯·åŠ¡å¿…å…ˆæŸ¥é˜…ä½¿ç”¨æ–‡æ¡£ï¼Œ90% çš„æ’­æ”¾é…ç½®é—®é¢˜éƒ½èƒ½åœ¨è¿™é‡Œæ‰¾åˆ°ç­”æ¡ˆã€‚"
    
  - name: "ğŸ” ç¬¬äºŒæ­¥ï¼šæœç´¢å·²æœ‰ Issue"
    url: https://github.com/liuchuancong/pure_live/issues
    about: "è¯·å…ˆæœç´¢å…³é”®è¯ï¼Œçœ‹çœ‹æ˜¯å¦å·²ç»æœ‰äººåé¦ˆè¿‡ç›¸åŒçš„é—®é¢˜ï¼Œé¿å…é‡å¤æäº¤ã€‚"
    
  - name: "ğŸ“¸ ç¬¬ä¸‰æ­¥ï¼šå‡†å¤‡æˆªå›¾æˆ–å½•å±(æ¨è)"
    url: https://github.com/liuchuancong/pure_live
    about: "å¦‚æœæ˜¯è§†é¢‘é»‘å±ã€æŠ¥é”™æˆ– UI å¼‚å¸¸ï¼Œè¯·åŠ¡å¿…å‡†å¤‡å¥½æ§åˆ¶å°æŠ¥é”™æˆªå›¾æˆ–ç°è±¡å½•å±ã€‚"
